CREATE database companydb1;
Use companydb1;


-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `SSN` INT NOT NULL,
  `PNAME` VARCHAR(45) NOT NULL,
  `MINIT` VARCHAR(45) NOT NULL,
  `LNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SSN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEPENDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPENDENT` (
  `dFNAME` VARCHAR(45) NOT NULL,
  `DEPENDENTcol` VARCHAR(45) NOT NULL,
  `LNAME` VARCHAR(45) NOT NULL,
  `GENDER` VARCHAR(45) NOT NULL,
  `RELATIONSHIP` VARCHAR(45) NOT NULL,
  `EMPLOYEE_SSN` INT NOT NULL,
  PRIMARY KEY (`dFNAME`, `EMPLOYEE_SSN`),
  INDEX `fk_DEPENDENT_EMPLOYEE_idx` (`EMPLOYEE_SSN` ASC),
  CONSTRAINT `fk_DEPENDENT_EMPLOYEE`
    FOREIGN KEY (`EMPLOYEE_SSN`)
    REFERENCES `EMPLOYEE` (`SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
